import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>

          <img src="/wasmer-logo.svg" alt="Wasmer" />
          <label for="site-search">Search packages, users or apps</label>
          <input type="search" id="site-search" name="q" />

          <nav><ul>
            <li>Products</li>
            <li>Developers</li>
            <li>Blog</li>
            <li>Templates</li>
            <li>GitHub</li>
            <li>Discord</li>
            <li>Sign in</li>
          </ul></nav>

        </header>
        {children}
      </body>

      <footer>
        <img src="/wasmer-logo.svg" alt="Wasmer" />
        <p>Making software universally accessible</p>
        <ul>
          <li>Imprint</li>
          <li>Privacy</li>
          <li>Terms</li>
        </ul>
      </footer>
    </html>
  );
}
